#pragma once

#include <ntddk.h>

#define UPPER_TRACE_EVENT_INJECT_REPORT_STORED   0x1001UL
#define UPPER_TRACE_EVENT_OVERRIDE_XINPUT_READ   0x1002UL
#define UPPER_TRACE_EVENT_OVERRIDE_XINPUT_IOCTL  0x1003UL
#define UPPER_TRACE_EVENT_OVERRIDE_HID_IOCTL     0x1004UL
#define UPPER_TRACE_EVENT_FORWARD_READ_REQUEST   0x1005UL
#define UPPER_TRACE_EVENT_FORWARD_COMPLETION     0x1006UL
#define UPPER_TRACE_EVENT_BUFFER_RESOLVE_FAILED  0x1007UL
#define UPPER_TRACE_EVENT_OBSERVATION_CAPTURED   0x1008UL

typedef struct _UPPER_TRACE_ENTRY {
    ULONGLONG TimestampQpc;
    ULONG EventCode;
    NTSTATUS Status;
} UPPER_TRACE_ENTRY, *PUPPER_TRACE_ENTRY;

VOID UpperTraceReset(VOID);
VOID UpperTraceRecord(_In_ ULONG EventCode, _In_ NTSTATUS Status);
