#pragma once

#ifndef GAYM_DEVICE_IDS_H
#define GAYM_DEVICE_IDS_H

#define GAYM_HARDWARE_ID_XBOX_02FF_WIDE L"HID\\VID_045E&PID_02FF&IG_00"
#define GAYM_HARDWARE_ID_XBOX_02FF_ANSI "HID\\VID_045E&PID_02FF&IG_00"

typedef enum _GAYM_ADAPTER_FAMILY {
    GAYM_ADAPTER_FAMILY_UNKNOWN = 0,
    GAYM_ADAPTER_FAMILY_XBOX_02FF = 1,
} GAYM_ADAPTER_FAMILY;

#endif
